application: connoisseurmenu
version: 1
runtime: python
api_version: 1

handlers:

- url: /static/css
  static_dir: static/css
  
- url: /static/img
  static_dir: static/img
  
- url: /static/js
  static_dir: static/js
  
- url: .*
  script: app.py
  
- url: /static/css/(.*\.appcache)
  static_files: static/css/\1
  mime_type: text/cache-manifest
  upload: static/css/(.*\.appcache)


